name: Build PGOV

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Compile ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64, arm32]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c
          add-to-path: false

      - name: Setup Ninja Build System
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Configure CMake Release
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: cmake --preset ${{ matrix.arch }}-release

      - name: Build Release
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: cmake --build --preset ${{ matrix.arch }}-release

      - name: Configure CMake Debug
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: cmake --preset ${{ matrix.arch }}-debug

      - name: Build Debug
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: cmake --build --preset ${{ matrix.arch }}-debug
